Heading:
  default: ""
  max: 25
  description:
    en: "Text for the heading in the footer - you can use your site name for example - Max length 25 characters"
Blurb:
  default: ""
  max: 180
  description:
    en: "Enter a short blurb about your community - Max length 180 characters"
Link_sections:
  type: list
  list_type: simple
  default: "Product | Integrations | Solutions | Resources | Community | Company"
  description:
    en: "Add link sections. The ideal number of sections is six. One item per line in this order:<br> Text, title<br><b>Text:</b> what appears on in the footer<br><b>Title:</b> the text that appears when the item is hovered."
Links:
  type: list
  list_type: simple
  default: >-
    Product, Overview,  https://netdata.cloud/product, _blank, A complete view of your infrastructure world |
    Product, Netdata Agent, https://www.netdata.cloud/agent/, _blank |
    Product, Netdata Cloud, https://www.netdata.cloud/cloud/, _blank |
    Product, Status, https://status.netdata.cloud/, _blank |
    Integrations, View all, https://www.netdata.cloud/integrations/, _blank |
    Integrations, Featured, https://www.netdata.cloud/integrations/#featured, _blank |
    Integrations, Services & apps, https://www.netdata.cloud/integrations/#service_app_collectors, _blank |
    Integrations, Systems, https://www.netdata.cloud/integrations/#system_collectors, _blank |
    Integrations, Notifications, https://www.netdata.cloud/integrations/#notifications, _blank |
    Integrations, Backends & exporters, https://www.netdata.cloud/integrations/#backends_exporters, _blank |
    Solutions, Containers, https://www.netdata.cloud/container-monitoring/, _blank |
    Solutions, Databases, https://www.netdata.cloud/database-monitoring/, _blank |
    Solutions, DevOps, https://www.netdata.cloud/devops-with-netdata/, blank |
    Solutions, Incident Management, https://www.netdata.cloud/incident-management/, _blank |
    Solutions, Web, https://www.netdata.cloud/web-server-monitoring/, _blank |
    Resources, Learn, https://learn.netdata.cloud, _blank |
    Resources, Blog, https://netdata.cloud/category/blog/, _blank |
    Resources, GitHub, https://github.com/netdata/netdata, _blank |
    Community, Overview, https://netdata.cloud/community/ _blank |
    Community, Forums, https://community.netdata.cloud, _blank |
    Company, About, https://netdata.cloud/about/, _blank |
    Company, News, https://netdata.cloud/news/, _blank |
    Company, Careers, https://careers.netdata.cloud, _blank |
  en: "Add links to link sections. One item per line in this order:<br>Parent, text, URL, target, title<br>It is a good idea to keep the number of links under each section similar<br><b>Parent:</b> the name of the parent section which this link shows under. Use the `text` value from the list above<br><b>Text:</b> the text that shows for this link<br><b>URL:</b> the path this item links to. You can use relative paths as well.<br><b>Target:</b> Choose whether this item will open in a new tab or in the same tab. Use blank to open the link in a new tab, or use self to open it in the same tab.<br><b>Title:</b> the text that shows when the link is hovered."
Small_links:
  type: list
  list_type: simple
  default: "Privacy Policy, https://www.netdata.cloud/privacy/, _blank|Terms of service, https://www.netdata.cloud/terms/, _blank| Code of Conduct, https://learn.netdata.cloud/contribute/code-of-conduct, _blank"
  description:
    en: "You can add small links at the bottom of the footer like Terms of Service and Privacy. One item per line in this order:<br>Text, URL, target<br><b>Text:</b> The text that shows for the small link<br><b>URL:</b> The path of the link<br><b>Target:</b> Use blank to open the link in a new tab and use self to open it in the same tab"
Social_links:
  type: list
  list_type: simple
  default: >-
    Facebook, Join us on Facebook, https://www.facebook.com/linuxnetdata/, blank,fab-facebook|
    Twitter, show some love on Twitter, https://twitter.com/linuxnetdata, blank,fab-twitter|
    Youtube, Check out our latest videos on Youtube, https://www.youtube.com/channel/UC61IDHAysha3o3QI-LTno7A, blank,fab-youtube|
    Reddit, Check out our reddit channel, https://www.reddit.com/r/netdata/, blank,fab-reddit|
    Linkedin, Checkout our Linkedin, https://www.linkedin.com/company/netdata-cloud, blank, fab-linkedin-in|
    Github, Join us on Github, https://github.com/netdata/netdata, blank, fab-github
  description:
    en: "Enter the social links you'd like to add to the footer in this format:<br> provider, title, URL, target<br><b>Provider:</b> is the name of the provider like Facebook or Twitter<br><b>Title:</b> The text that shows when the link is hovered<br><b>URL:</b> The path you'd like the link to have<br><b>Target:</b> Use blank to open the link in a new tab and use self to open it in the same tab<br><b>Icon:</b> use a FontAwesome5 icon name (brand icons need a 'fab-' prefix)."
svg_icons:
  default: "fab-facebook|fab-twitter|fab-youtube|fab-reddit|fab-linkedin-in|fab-github"
  type: "list"
  list_type: "compact"
  description: "List of FontAwesome 5 icons used in the social links setting above. "
